/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.List;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JPrincipal
     */
    public FPrincipal() {
        initComponents();
    }
    
    Random random = new Random();
    
    ImageIcon cartas[] = {new ImageIcon(getClass().getResource("/formularios/imagens/cartaTeste1.png")),
                    new ImageIcon(getClass().getResource("/formularios/imagens/cartaTeste2.png")),
                    new ImageIcon(getClass().getResource("/formularios/imagens/cartaTeste3.png")),
                    new ImageIcon(getClass().getResource("/formularios/imagens/cartaTeste4.png"))};
    
    ArrayList<Integer> cartasUsadas = new ArrayList();
    String[] lstResposta = {"a", "b", "a", "c"};

    String resposta = "";
    int acertos = 0;
    int erros = 0;
    
    int index;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        lblCarta = new javax.swing.JLabel();
        btnResposta = new javax.swing.JButton();
        rdbA = new javax.swing.JRadioButton();
        rdbB = new javax.swing.JRadioButton();
        rdbC = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblAcerto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIniciar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/imagens/musculoTeste.PNG"))); // NOI18N

        btnResposta.setText("Enviar");
        btnResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbA);
        rdbA.setText("A");
        rdbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbB);
        rdbB.setText("B");
        rdbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbBActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbC);
        rdbC.setText("C");
        rdbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Acertos");

        lblAcerto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcerto.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Erros");

        lblErro.setText("-");
        lblErro.setMaximumSize(new java.awt.Dimension(5, 17));
        lblErro.setMinimumSize(new java.awt.Dimension(5, 17));

        menuIniciar.setText("Iniciar Jogo");
        menuIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIniciarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuIniciar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblAcerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rdbA)
                        .addGap(114, 114, 114)
                        .addComponent(rdbB)
                        .addGap(103, 103, 103)
                        .addComponent(rdbC))
                    .addComponent(lblCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblAcerto)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbA)
                            .addComponent(rdbB)
                            .addComponent(rdbC))
                        .addGap(38, 38, 38)
                        .addComponent(btnResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        btnResposta.setVisible(false);
        rdbA.setVisible(false);
        rdbB.setVisible(false);
        rdbC.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarImagem(){
        index = random.nextInt(cartas.length);
                
            while(cartasUsadas.contains(index)){
                index = random.nextInt(cartas.length);
                
                if(cartasUsadas.size() == cartas.length){

                   if(JOptionPane.showConfirmDialog(this, "As cartas acabaram! Deseja recomeçar? \n\n", "Fim de jogo",
                           JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){

                        cartasUsadas.clear();
                        acertos = 0;
                        erros = 0;
                        lblAcerto.setText(Integer.toString(acertos));
                        lblErro.setText(Integer.toString(erros));
                        
                        index = random.nextInt(cartas.length);

                        break;

                   }else{
                       System.exit(0);
                   }
                }
            }
        cartasUsadas.add(index);    
        lblCarta.setIcon(cartas[index]);
    }
    
    private void btnRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostaActionPerformed
        try{
 
            if(!resposta.equals("")){
                if(resposta.equals(lstResposta[index].toLowerCase())){
                    acertos++;
                    JOptionPane.showMessageDialog(this, "Acertou!");

                }else{
                    erros++;
                    JOptionPane.showMessageDialog(this, "Errou! A resposta era -" + lstResposta[index].toUpperCase() + "-\n\n", resposta, index, cartas[index]);
                }

                lblAcerto.setText(Integer.toString(acertos));
                lblErro.setText(Integer.toString(erros));

                carregarImagem();
            }else{
                JOptionPane.showMessageDialog(this, "Selecione uma resposta!");
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Não foi possível realizar a ação \n\n" + ex.getMessage(), "Ops", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnRespostaActionPerformed

    private void rdbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbBActionPerformed
        if(rdbB.isSelected()){
                resposta = "b";
            }
    }//GEN-LAST:event_rdbBActionPerformed

    private void menuIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIniciarMouseClicked
        rdbA.setVisible(true);
        rdbB.setVisible(true);
        rdbC.setVisible(true);
        btnResposta.setVisible(true);
        
        carregarImagem();
    }//GEN-LAST:event_menuIniciarMouseClicked

    private void rdbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAActionPerformed
        if(rdbA.isSelected()){
                resposta = "a";
            }
    }//GEN-LAST:event_rdbAActionPerformed

    private void rdbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCActionPerformed
        if(rdbC.isSelected()){
                resposta = "c";
            }
    }//GEN-LAST:event_rdbCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResposta;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAcerto;
    private javax.swing.JLabel lblCarta;
    private javax.swing.JLabel lblErro;
    private javax.swing.JMenu menuIniciar;
    private javax.swing.JRadioButton rdbA;
    private javax.swing.JRadioButton rdbB;
    private javax.swing.JRadioButton rdbC;
    // End of variables declaration//GEN-END:variables
}
